### ISSUE TITLE
Cannot query data to Node-Red ( "ReferenceError: e is not defined" )

### ISSUE THREAD

**Issue by MosheSabag** [kp45-tech/node-red-contrib-tdengine#4]
![Screenshot 2024-04-28 103558](https://github.com/kp45-tech/node-red-contrib-tdengine/assets/44094621/f4102756-ca08-4b18-b530-cc3d0cb4b3c1)

Hello,
I'm getting this error message although I try to do exactly what is written in the example in Git. 
I have a working connection to TDEngine database locally but from some reason I get the error message :"ReferenceError: e is not defined":

**Comment by kevinpan45** [comment]
what's your TDEngine version

**Comment by kevinpan45** [comment]
your should initial some test data, see [the official doc section](https://docs.tdengine.com/get-started/package/#tdengine-command-line-interface)
version 0.0.5 is publish and available

**Comment by kevinpan45** [comment]
> ![Screenshot 2024-04-28 103558](https://private-user-images.githubusercontent.com/44094621/326239712-f4102756-ca08-4b18-b530-cc3d0cb4b3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDQxMjcsIm5iZiI6MTczMjI0MzgyNywicGF0aCI6Ii80NDA5NDYyMS8zMjYyMzk3MTItZjQxMDI3NTYtY2EwOC00YjE4LWI1MzAtY2MzZDBjYjRiM2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAyNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NDhkNTI5MGYyMjg3YWJkNTFiYzVjYWRmYzU2ZGQwOTRkMDY2NzhhMjdiNTU1NGUzZTIyOTRiNGY1ZGFlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PHWLVVFhFLAXF2xvRIckm2Qyz8_5buA6EuAYn0zYroE)
> 
> Hello, I'm getting this error message although I try to do exactly what is written in the example in Git. I have a working connection to TDEngine database locally but from some reason I get the error message :"ReferenceError: e is not defined":

new version of TDEngine restful API port is changed, I had fix it
