### ISSUE TITLE
提几个功能小建议

### ISSUE THREAD

**Issue by ichrislu** [kp45-tech/node-red-contrib-tdengine#6]
能否支持websocket连接方式、stmt参数绑定和批处理，万分感谢🙏

**Comment by kevinpan45** [comment]
支持websocket得另外写一个插件了吧，不同协议增加了配置复杂度和使用时候的区分

**Comment by kevinpan45** [comment]
不太确定你说的批处理场景是指什么，如果是需要单独执行多个独立的SQL，可以前置node-red的内置的Node作为队列逻辑实现，或者使用类似kafka这样的Node去订阅队列实现

**Comment by ichrislu** [comment]
只是突发的一个极端场景：边缘端采集的数据不经过Broker直接入库，用“tdengine”关键字找到这个node，试了一下select，验证了技术可行性。
因为是长期固定的数据库操作，所以希望是基于ws的长连接；插入数据比较多的，用stmt+batch更高效。
直连入库，目的就是想省掉一个队列，中间不需要MQ。

**Comment by kevinpan45** [comment]
> 现在是前置MQ的方式，自己用Go写了一个消费端入库，就是ws + batch，示例如下：
> 
> ` pstmt, err := conn.Init() if err != nil { return err }
> 
> ```
> _sql := "INSERT INTO ? USING em TAGS (?) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
> err = pstmt.Prepare(_sql)
> if err != nil {
> 	return err
> }
> 
> for _, data := range msg.Data {
> 	err = pstmt.SetTableName(data.Device)
> 	if err != nil {
> 		return err
> 	}
> 
> 	tags := param.NewParam(1).AddUInt(uint(msg.Project))
> 	tagsType := param.NewColumnType(1).AddUInt()
> 	err = pstmt.SetTags(tags, tagsType)
> 	if err != nil {
> 		return err
> 	}
> 
> 	columnsType := param.NewColumnType(22).AddTimestamp().AddDouble().AddDouble().AddDouble().AddDouble().
> 		AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().
> 		AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().AddDouble().
> 		AddDouble()
> 	columns := make([]*param.Param, 22)
> 	columns[0] = param.NewParam(1).AddTimestamp(time.UnixMilli(int64(ts)), common.PrecisionMilliSecond)
> 	err = pstmt.BindParam(columns, columnsType)
> 	......
> 	err = pstmt.AddBatch()
> 	if err != nil {
> 		return err
> 	}
> }
> 
> err = pstmt.Exec()
> ```
> 
> `

比较好奇这个批量操作如果其中某一条失败了是这一批一起回滚吗，事务的策略是什么

**Comment by kevinpan45** [comment]
this issue is not suitable for this plugin
